"""Module to retrieve useful data through dictionaries. (Note: originally 
stored in helper files, but exporting the project as a single executable 
file requires no attached data, only code).
"""

import pandas as pd

ISO639_MAP = {
    'aa': 'aar', 'ab': 'abk', 'af': 'afr', 'ak': 'aka', 'am': 'amh', 
    'ar': 'ara', 'an': 'arg', 'as': 'asm', 'av': 'ava', 'ae': 'ave', 
    'ay': 'aym', 'az': 'aze', 'ba': 'bak', 'bm': 'bam', 'be': 'bel', 
    'bn': 'ben', 'bi': 'bis', 'bo': 'bod', 'bs': 'bos', 'br': 'bre', 
    'bg': 'bul', 'ca': 'cat', 'cs': 'ces', 'ch': 'cha', 'ce': 'che', 
    'cu': 'chu', 'cv': 'chv', 'kw': 'cor', 'co': 'cos', 'cr': 'cre', 
    'cy': 'cym', 'da': 'dan', 'de': 'deu', 'dv': 'div', 'dz': 'dzo', 
    'el': 'ell', 'en': 'eng', 'eo': 'epo', 'et': 'est', 'eu': 'eus', 
    'ee': 'ewe', 'fo': 'fao', 'fa': 'fas', 'fj': 'fij', 'fi': 'fin', 
    'fr': 'fra', 'fy': 'fry', 'ff': 'ful', 'gd': 'gla', 'ga': 'gle', 
    'gl': 'glg', 'gv': 'glv', 'gn': 'grn', 'gu': 'guj', 'ht': 'hat', 
    'ha': 'hau', 'sh': 'hbs', 'he': 'heb', 'hz': 'her', 'hi': 'hin', 
    'ho': 'hmo', 'hr': 'hrv', 'hu': 'hun', 'hy': 'hye', 'ig': 'ibo', 
    'io': 'ido', 'ii': 'iii', 'iu': 'iku', 'ie': 'ile', 'ia': 'ina', 
    'id': 'ind', 'ik': 'ipk', 'is': 'isl', 'it': 'ita', 'jv': 'jav', 
    'ja': 'jpn', 'kl': 'kal', 'kn': 'kan', 'ks': 'kas', 'ka': 'kat', 
    'kr': 'kau', 'kk': 'kaz', 'km': 'khm', 'ki': 'kik', 'rw': 'kin', 
    'ky': 'kir', 'kv': 'kom', 'kg': 'kon', 'ko': 'kor', 'kj': 'kua', 
    'ku': 'kur', 'lo': 'lao', 'la': 'lat', 'lv': 'lav', 'li': 'lim', 
    'ln': 'lin', 'lt': 'lit', 'lb': 'ltz', 'lu': 'lub', 'lg': 'lug', 
    'mh': 'mah', 'ml': 'mal', 'mr': 'mar', 'mk': 'mkd', 'mg': 'mlg', 
    'mt': 'mlt', 'mn': 'mon', 'mi': 'mri', 'ms': 'msa', 'my': 'mya', 
    'na': 'nau', 'nv': 'nav', 'nr': 'nbl', 'nd': 'nde', 'ng': 'ndo', 
    'ne': 'nep', 'nl': 'nld', 'nn': 'nno', 'nb': 'nob', 'no': 'nor', 
    'ny': 'nya', 'oc': 'oci', 'oj': 'oji', 'or': 'ori', 'om': 'orm', 
    'os': 'oss', 'pa': 'pan', 'pi': 'pli', 'pl': 'pol', 'pt': 'por', 
    'ps': 'pus', 'qu': 'que', 'rm': 'roh', 'ro': 'ron', 'rn': 'run', 
    'ru': 'rus', 'sg': 'sag', 'sa': 'san', 'si': 'sin', 'sk': 'slk', 
    'sl': 'slv', 'se': 'sme', 'sm': 'smo', 'sn': 'sna', 'sd': 'snd', 
    'so': 'som', 'st': 'sot', 'es': 'spa', 'sq': 'sqi', 'sc': 'srd', 
    'sr': 'srp', 'ss': 'ssw', 'su': 'sun', 'sw': 'swa', 'sv': 'swe', 
    'ty': 'tah', 'ta': 'tam', 'tt': 'tat', 'te': 'tel', 'tg': 'tgk', 
    'tl': 'tgl', 'th': 'tha', 'ti': 'tir', 'to': 'ton', 'tn': 'tsn', 
    'ts': 'tso', 'tk': 'tuk', 'tr': 'tur', 'tw': 'twi', 'ug': 'uig', 
    'uk': 'ukr', 'ur': 'urd', 'uz': 'uzb', 've': 'ven', 'vi': 'vie', 
    'vo': 'vol', 'wa': 'wln', 'wo': 'wol', 'xh': 'xho', 'yi': 'yid', 
    'yo': 'yor', 'za': 'zha', 'zh': 'zho', 'zu': 'zul', 'zxx': 'zxx'
}
"""Dictionary mapping languages codes ISO639-1 to ISO639-3."""

FORMATS = pd.DataFrame({
    'format': [
        '7z', 'AAC', 'AIFF', 'ALAC', 'Android Application', 'Apache Avro', 
        'Apache Parquet', 'Apache ORC', 'APNG', 'APRX', 'ASCII Grid', 'AV1', 
        'AVI', 'AVIF', 'Avro', 'B1', 'BAG', 'BAM', 'Blackerry Application', 
        'BMP', 'BWF', 'BZIP2', 'CCT', 'CDED ASCII', 'Common Data Format', 
        'Computable Data Format', 'CDR', 'CMML', 'COG', 'Collada', 'CSS', 
        'CSV', 'DAE', 'DAISY', 'DBD', 'DBF', 'DICOM', 
        'Digital Accessible Information System', 'Dirac', 'DITA', 'DjVu', 
        'DNG', 'DOC', 'DocBook', 'DOCX', 'DVI', 'DXF', 'E00', 'EAS3', 'ECW', 
        'EDI', 'ELF', 'EMF', 'EPS', 'EPUB2', 'EPUB3', 'ESRI REST', 'FGDB/GDB',
        'FictionBook', 'FITS', 'FLAC', 'Flat raster binary', 'FLIF', 
        'Gerber File', 'GIMP Brush File', 'GEOJSON', 'GeoPackage', 'GeoPDF', 
        'GeoRSS', 'GeoSoftDatabases', 'GeoSoftGrids', 'GeoTIF', 'GeoTIFF', 
        'GIF', 'glTF', 'GML', 'GPX', 'GRIB1', 'GRIB2', 'Gzip', 'HDF', 
        'HSQLDB', 'HTML', 'IATI', 'iCalendar', 'IFS', 'InfoSlips Package', 
        'INI', 'iOS Application', 'JAR', 'JFIF', 'JP2', 'JPG', 'JPEG', 
        'JPEG 2000', 'JPEG XL', 'JSON', 'JSONL', 'JSON-LD', 'KML', 'KMZ', 
        'LAS', 'LaTeX', 'LTFS', 'LYR', 'lzp', 'MAFF', 'MapInfo', 'MAPX', 
        'Markdown', 'Matroska', 'MFX', 'MNG', 'MOV', 'MPEG', 'MPEG-1', 
        'MPEG-4', 'MP3', 'MP4', 'Musepack', 'MXD', 'MXF', 'NetCDF', 'NZB', 
        'OBJ', 'ODP', 'ODS', 'ODT', 'Office Open XML', 'Ogg', 'Ogg Theora', 
        'Ogg Vorbis', 'OpenEXR', 'OpenRaster', 'OpenSMILES', 'OpenType', 
        'OpenXPS', 'Opus', 'ORC', 'OTF', 'Other', 'OOXML', 'Parquet', 'PAQ', 
        'PBF', 'PBIX', 'PDF', 'PDF/A-1', 'PDF/A-2', 'PDF/E', 'PDF/UA', 
        'PDF/X', 'PNG', 'PostScript', 'PPT', 'PPTX', 'QLR', 'QOI', 
        'QuickTime File Format', 'RDF', 'RDF n-triples', 'RDF n-quads', 
        'RDF TriG', 'RDF Turtle', 'RDFa', 'RSS', 'RTF', 'SAM', 'SAS', 
        'SAV (SPSS)', 'SDXF', 'SFV', 'SEGY', 'Shapefile', 'SHP', 'SMIL', 
        'SMILES', 'Speex', 'SQL', 'SQL Lite', 'SQL Lite3', 'SQX', 'SVG', 
        'STL', 'TAR', 'TFW', 'Theora', 'TIF', 'TIFF', 'TOML', 'TRIG', 'TRIX',
        'TrueType', 'TSV', 'TTF', 'TXT', 'Unknown', 'vCard', 'Vorbis', 
        'VRML/X3D', 'VPF', 'WAV', 'WavPack', 'WCS', 'WebM', 'WebP', 'WFS', 
        'WOFF', 'WOFF2', 'WMS', 'WMTS', 'WMV', 'WPS', 'X3D', 'XCF', 'XHTML', 
        'XLS', 'XLSM', 'XLSX', 'XML', 'XPM', 'XSLT', 'XSPF', 'XZ', 'XZ Utils', 
        'YAML', 'ZIM', 'ZIP'
    ],
    'format_type': [
        'Archive', 'Audio', 'Audio', 'Image', 'Application', 'Structured Data', 
        'Structured Data', 'Structured Data', 'Image', 'Geospatial Data', 
        'Text Document', 'Video', 'Video', 'Video', 'Structured Data', 'Archive', 
        'Geospatial Data', 'Specialized Format', 'Application', 'Image', 
        'Audio', 'Archive', 'Specialized Format', 'Geospatial Data', 
        'Specialized Format', 'Specialized Format', 'Image', 
        'Specialized Format', 'Geospatial Data', 'Specialized Format', 
        'Specialized Format', 'Structured Data', 'Specialized Format', 
        'Audio', 'Database', 'Database', 'Image', 'Audio', 'Video', 
        'Structured Data', 'Image', 'Image', 'Text Document', 'Text Document',
        'Text Document', 'Text Document', 'Specialized Format', 
        'Geospatial Data', 'Specialized Format', 'Geospatial Data', 
        'Specialized Format', 'Specialized Format', 'Image', 'Image', 
        'Text Document', 'Text Document', 'Geospatial Data', 
        'Geospatial Data', 'Text Document', 'Specialized Format', 'Audio', 
        'Geospatial Data', 'Image', 'Image', 'Image', 'Geospatial Data', 
        'Geospatial Data', 'Geospatial Data', 'Geospatial Data', 
        'Geospatial Data', 'Geospatial Data', 'Geospatial Data', 
        'Geospatial Data', 'Image', 'Specialized Format', 'Geospatial Data', 
        'Geospatial Data', 'Geospatial Data', 'Geospatial Data', 'Archive', 
        'Database', 'Database', 'Web Page', 'Structured Data', 
        'Specialized Format', 'Specialized Format', 'Specialized Format', 
        'Specialized Format', 'Application', 'Archive', 'Image', 'Image', 
        'Image', 'Image', 'Image', 'Image', 'Structured Data', 
        'Structured Data', 'Structured Data', 'Geospatial Data', 
        'Geospatial Data', 'Geospatial Data', 'Text Document', 
        'Specialized Format', 'Geospatial Data', 'Archive', 'Archive', 
        'Geospatial Data', 'Geospatial Data', 'Text Document', 'Video', 
        'Video', 'Image', 'Video', 'Video', 'Video', 'Video', 'Audio', 
        'Video', 'Audio', 'Geospatial Data', 'Video', 'Geospatial Data', 
        'Structured Data', 'Specialized Format', 'Presentation', 
        'Structured Data', 'Text Document', 'Structured Data', 'Video', 
        'Video', 'Audio', 'Image', 'Image', 'Specialized Format', 
        'Specialized Format', 'Text Document', 'Audio', 'Structured Data', 
        'Specialized Format', 'Specialized Format', 'Structured Data', 
        'Structured Data', 'Archive', 'Geospatial Data', 'Specialized Format', 
        'Text Document', 'Text Document', 'Text Document', 'Text Document', 
        'Text Document', 'Text Document', 'Image', 'Text Document', 
        'Presentation', 'Presentation', 'Geospatial Data', 'Image', 'Video', 
        'Structured Data', 'Structured Data', 'Structured Data', 'Structured Data', 
        'Structured Data', 'Structured Data', 'Structured Data', 'Text Document', 
        'Specialized Format', 'Specialized Format', 'Specialized Format', 
        'Structured Data', 'Specialized Format', 'Geospatial Data', 
        'Geospatial Data', 'Geospatial Data', 'Specialized Format', 
        'Specialized Format', 'Audio', 'Database', 'Database', 'Database', 
        'Archive', 'Image', 'Specialized Format', 'Archive', 
        'Geospatial Data', 'Video', 'Image', 'Image', 'Specialized Format', 
        'Structured Data', 'Structured Data', 'Specialized Format', 'Structured Data',
        'Specialized Format', 'Text Document', 'Specialized Format', 
        'Specialized Format', 'Audio', 'Specialized Format', 
        'Geospatial Data', 'Audio', 'Audio', 'Geospatial Data', 'Video', 
        'Image', 'Geospatial Data', 'Specialized Format', 
        'Specialized Format', 'Geospatial Data', 'Geospatial Data', 'Video', 
        'Text Document', 'Specialized Format', 'Image', 'Structured Data', 
        'Structured Data', 'Structured Data', 'Structured Data', 
        'Structured Data', 'Image', 'Structured Data', 'Specialized Format', 
        'Archive', 'Archive', 'Structured Data', 'Text Document', 'Archive'
    ],
    'open': [
        True, False, False, True, True, True, True, True, True, False, True, 
        True, False, True, True, True, True, True, False, True, True, True, 
        False, True, True, False, False, True, True, True, True, True, True, 
        True, False, True, True, True, True, True, True, True, False, True, 
        False, True, True, True, True, False, True, True, False, True, True, 
        True, True, False, True, True, True, True, True, True, True, True, 
        True, False, True, False, False, True, True, True, True, True, True, 
        True, True, True, True, True, True, True, True, False, True, True, 
        False, True, True, True, True, True, True, True, True, True, True, 
        True, True, True, True, True, False, True, True, False, False, True, 
        True, True, True, False, True, True, False, True, False, True, False, 
        True, True, True, True, True, True, True, True, True, True, True, 
        True, True, True, True, True, True, True, True, True, True, True, 
        True, True, False, True, True, True, True, True, True, True, True, 
        False, False, True, True, False, True, True, True, True, True, True, 
        True, True, True, False, False, True, True, True, True, True, True, 
        False, True, True, True, True, True, True, True, True, True, True, 
        True, True, True, True, True, True, True, True, True, True, True, 
        True, True, True, False, True, True, True, True, True, True, True, 
        True, True, False, False, True, True, True, False, False, False, 
        True, True, True, True, True, True, True, True, True
    ]
})
"""DataFrame containing info about files formats (type of format and openness)
"""
